Tasks 5/7.1/7.3
InVanSav/Scrubs pull request #4
Opened 2023-01-13 17:23 UTC by InVanSav

Сделал все задания. В названии коммита написано, какие именно здесь задания. 
Асинхронные методы у меня были с самого начала, поэтому не все будут в этом коммите.

И еще, у меня проблема есть. Я забыл пароль от бд. И смешно, и нет звучит, честно говоря..
Поэтому на скринах увидите результат. Если это чересчур критично, то я буду думать, как исправить ситуацию.

Ну и, на скринах впринципе показано, где выдает ошибку, что пользователь не авторизован, что все работает.
Если не считать бд.

![Снимок экрана 2023-01-14 в 02 18 57](https://user-images.githubusercontent.com/101239105/212380542-33de3bf2-72ea-4161-85d5-c133cf145afd.png)
![Снимок экрана 2023-01-14 в 02 19 44](https://user-images.githubusercontent.com/101239105/212380560-645a034e-9472-451b-84bd-08c3d6297678.png)
![Снимок экрана 2023-01-14 в 02 16 49](https://user-images.githubusercontent.com/101239105/212380564-27010263-2f19-4494-b1d3-ede8445c484f.png)

2023-01-14 06:23 UTC, Vixorem requested changes

2023-01-14 06:23 UTC, Vixorem commented on Scrubs.Service/Implementations/AppointmentDoctorService.cs
>              var appointment = _appointmentDoctorRepository.Get(id);
Здесь нет await'а и из зп этого ниже вы неправильно работаете с асинхроном. Вы ниже лезете в . Result, и так делать не надо. Ну и в остальных местах аналогично

2023-01-14 07:53 UTC, InVanSav commented
Этот момент исправил

2023-01-15 05:03 UTC, Vixorem approved these changes

2023-01-15 05:03 UTC, merged